### ISSUE TITLE
[BUG] Gemini API is not working

### ISSUE THREAD

**Issue by wedlj2094** [Renset/macai#37]
**Describe the bug**
When using macai v2.0.0-beta.1
While "Test API token & model" did work when adding Gemini APi key.
In real chats, It is just completely broken, showing blank text in both user prompt and gemini response.
BTW, I'm using Google AI studio's API key, not Vertex AI's api key.

**To Reproduce**
1. add Google AI studio API key
2. Test with basic chat
4. It does not work

**Expected behavior**
chat should work

**Screenshots**

https://github.com/user-attachments/assets/5a2da560-d729-4436-8fb3-ddc8039ed21a

**Environment:**
 - OS version: macOS Sequoia 15.2
- Architecture: arm64

**Comment by Renset** [comment]
@wedlj2094 unfortunately I can't reproduce this right now, because Google API is broken for me and returns 429 (Resource has been exhausted (e.g. check quota)) for my API keys for absolutely no reason. But it definitely worked for me with gemini-1.5-flash in the past. Could you try checking with this model? Could you also try turning on/off stream responses?

**Comment by wedlj2094** [comment]
I tested more, and the issue was stream response option.
If I turn off stream response, every Gemini models (including new experimental models) work.

**Comment by Renset** [comment]
@wedlj2094 Thanks, that was really helpful. My Gemini API started working again and I was able to reproduce, find the root cause and fix the problem. 

The reason was in Gemini API response, that has changed slightly. The current fix should make macai more tolerant of small API changes from OpenAI-like APIs.

**Comment by Renset** [comment]
The fix is already released with the [beta 2](https://github.com/Renset/macai/releases/tag/v2.0.0-beta.2)
