### ISSUE TITLE
Fix "Check for Updates" functionality

### ISSUE THREAD

**Issue by pmusolino** [Renset/macai#41]
I noticed that a release candidate for version 2.0.0 is available, but I was using an alpha version and discovered that the "Check for updates" feature isn't functioning as expected. It should notify users of new versions.

**Comment by Renset** [comment]
@pmusolino this is intended, because until release, things are change fast. As 2.0.0 is not yet a 'release' version, it is not available from the updater. When 2.0.0 is finally released, it should be available via the updater for all previous versions, including beta and RC (ETA is this week).
Since it's not a real issue, I'll close this now, but thanks for bringing it to my attention!
